FROM bordellio/base

RUN npm set progress=false

# Install Chrome
RUN sed -i -e 's/v3.8/edge/g' /etc/apk/repositories
RUN apk add --no-cache build-base
RUN apk add --no-cache chromium-chromedriver 
RUN apk add --no-cache chromium 
RUN apk upgrade --no-cache --available
ENV CHROME_BIN /usr/bin/chromium-browser

# TODO Copy in NPM cache
# RUN echo "Uploading npm cache to image..."
# RUN npm cache verify
# WORKDIR /npm
# COPY . .
# WORKDIR /work-dir
# RUN npm cache verify