FROM bordellio/base:latest

WORKDIR /project

# Install dependencies
COPY node_modules* ./node_modules
COPY package*.json ./
RUN npm install

# Lint, test and build app
COPY . ./
RUN npm run lint
RUN npm run test
RUN npm run build
