FROM bordellio/base:latest

WORKDIR /project

# Install dependencies
COPY package*.json node_modules ./
RUN npm install

# Lint, test and build app
COPY . ./
RUN npm run lint
RUN npm run test
RUN npm run build
