FROM olliecaine/base:master

WORKDIR /project

# Install Chrome
RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
    && echo http://dl-cdn.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories \
    && echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories \
    && apk --no-cache update && apk --no-cache upgrade \
    && apk add --no-cache \
      gifsicle \
      pngquant \
      optipng \
      libjpeg-turbo-utils \
      udev \
      ttf-opensans \
      nss \
      make \
      python \      
      freetype \
      harfbuzz \
      ttf-freefont \
      freetype-dev \
      chromium \
    && rm -rf /var/cache/apk/* /tmp/*

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/ \
    LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/chromium-browser
